# Generated by Django 5.0.4 on 2024-07-29 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.cliente'),
            preserve_default=False,
        ),
    ]
